Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> import numpy as np
... import matplotlib.pyplot as plt
... from montecarlo import MonteCarlo_double
... 
... 
... def f(x, y):
...     return x**2 + y**2
... 
... 
... def g(x, y):
...     return x**2 + y**2 - 1.5**2
... 
... 
... x0, x1 = -1.5, 1.5
... y0, y1 = -1.5, 1.5
... 
... 
... n = 10000
... 
... 
... area = MonteCarlo_double(f, g, x0, x1, y0, y1, n)
... 
... print("Area of the circle with radius 1.5:", area)
... 
... 
... theta = np.linspace(0, 2*np.pi, 100)
... x_circle = 1.5 * np.cos(theta)
... y_circle = 1.5 * np.sin(theta)
... 
... plt.figure(figsize=(6, 6))
... plt.scatter(np.random.uniform(x0, x1, n), np.random.uniform(y0, y1, n), s=1, color='b', alpha=0.5)
... plt.plot(x_circle, y_circle, color='r')
... plt.xlabel('x')
... plt.ylabel('y')
... plt.title('Monte Carlo Integration of Circle')
... plt.grid(True)
... plt.show()
